name: PHP Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: ['8.2']

    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: dom, curl, fileinfo, json, mbstring, pdo_sqlite, sqlite3
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run test suite
      run: ./vendor/bin/pest
